// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    
    #region Windows Form Designer generated code
    public partial class Form1
    {
        private void InitializeComponent()
        {
            this.Start1 = new System.Windows.Forms.Button();
            this.Start2 = new System.Windows.Forms.Button();
            this.tbX = new System.Windows.Forms.TextBox();
            this.tbY = new System.Windows.Forms.TextBox();
            this.addButton = new System.Windows.Forms.Button();
            this.Clear = new System.Windows.Forms.Button();
            this.Stop = new System.Windows.Forms.Button();
            this.graphPanel = new System.Windows.Forms.Panel();
            this.grid = new System.Windows.Forms.Button();
            // 
            // Start1
            // 
            this.Start1.Name = "Start1";
            this.Start1.Location = new System.Drawing.Point(615, 13);
            this.Start1.TabIndex = 0;
            this.Start1.Size = new System.Drawing.Size(87, 25);
            this.Start1.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.Start1.Text = "Start 1";
            this.Start1.UseVisualStyleBackColor = true;
            this.Start1.Click += new System.EventHandler(this.button1_Click);
            // 
            // Start2
            // 
            this.Start2.Name = "Start2";
            this.Start2.Location = new System.Drawing.Point(615, 44);
            this.Start2.TabIndex = 1;
            this.Start2.Size = new System.Drawing.Size(87, 25);
            this.Start2.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.Start2.Text = "Start 2";
            this.Start2.UseVisualStyleBackColor = true;
            this.Start2.Click += new System.EventHandler(this.button2_Click);
            // 
            // tbX
            // 
            this.tbX.Name = "tbX";
            this.tbX.ForeColor = System.Drawing.SystemColors.WindowText;
            this.tbX.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbX.Location = new System.Drawing.Point(615, 75);
            this.tbX.TabIndex = 2;
            this.tbX.Size = new System.Drawing.Size(87, 24);
            this.tbX.BackColor = System.Drawing.SystemColors.Window;
            this.tbX.Text = "X-koordinat";
            // 
            // tbY
            // 
            this.tbY.Name = "tbY";
            this.tbY.ForeColor = System.Drawing.SystemColors.WindowText;
            this.tbY.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbY.Location = new System.Drawing.Point(615, 108);
            this.tbY.TabIndex = 3;
            this.tbY.Size = new System.Drawing.Size(87, 24);
            this.tbY.BackColor = System.Drawing.SystemColors.Window;
            this.tbY.Text = "Y-koordinat";
            // 
            // addButton
            // 
            this.addButton.Name = "addButton";
            this.addButton.Location = new System.Drawing.Point(615, 140);
            this.addButton.TabIndex = 4;
            this.addButton.Size = new System.Drawing.Size(87, 25);
            this.addButton.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.addButton.Text = "Add";
            this.addButton.UseVisualStyleBackColor = true;
            this.addButton.Click += new System.EventHandler(this.addButton_Click);
            // 
            // Clear
            // 
            this.Clear.Name = "Clear";
            this.Clear.Location = new System.Drawing.Point(615, 296);
            this.Clear.TabIndex = 6;
            this.Clear.Size = new System.Drawing.Size(87, 25);
            this.Clear.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.Clear.Text = "Clear";
            this.Clear.UseVisualStyleBackColor = true;
            this.Clear.Click += new System.EventHandler(this.Clear_Click);
            // 
            // Stop
            // 
            this.Stop.Name = "Stop";
            this.Stop.Location = new System.Drawing.Point(615, 265);
            this.Stop.TabIndex = 5;
            this.Stop.Size = new System.Drawing.Size(87, 25);
            this.Stop.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.Stop.Text = "Stop graphs";
            this.Stop.UseVisualStyleBackColor = true;
            this.Stop.Click += new System.EventHandler(this.Stop_Click);
            // 
            // panel1
            // 
            this.graphPanel.Name = "graphPanel";
            this.graphPanel.TabIndex = 7;
            this.graphPanel.Size = new System.Drawing.Size(608, 560);
            this.graphPanel.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.graphPanel.Text = "graphPanel";
            this.graphPanel.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // Lol
            // 
            this.grid.Name = "Gridlines";
            this.grid.Location = new System.Drawing.Point(615, 394);
            this.grid.TabIndex = 8;
            this.grid.Size = new System.Drawing.Size(87, 25);
            this.grid.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.grid.Text = "Gridlines";
            this.grid.UseVisualStyleBackColor = true;
            this.grid.Click += new System.EventHandler(this.grid_Click);
            // 
            // Form1
            // 
            this.Name = "Graph Editor";
            this.ClientSize = new System.Drawing.Size(716, 561);
            this.Controls.Add(this.grid);
            this.Controls.Add(this.graphPanel);
            this.Controls.Add(this.Stop);
            this.Controls.Add(this.Clear);
            this.Controls.Add(this.tbX);
            this.Controls.Add(this.tbY);
            this.Controls.Add(this.addButton);
            this.Controls.Add(this.Start2);
            this.Controls.Add(this.Start1);
            this.Text = "Graph Editor";
        }
        private System.Windows.Forms.Button Start1;
        private System.Windows.Forms.Button Start2;
        private System.Windows.Forms.TextBox tbX;
        private System.Windows.Forms.TextBox tbY;
        private System.Windows.Forms.Button addButton;
        private System.Windows.Forms.Button Clear;
        private System.Windows.Forms.Button Stop;
        private System.Windows.Forms.Panel graphPanel;
        private System.Windows.Forms.Button grid;
    }
    #endregion
}
